Update patch set 2
Patch Set 2:

Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.614386 | rdo-centos-7 |            Requires: python2-networking-sfc >= 6.0.0
2019-03-22 12:47:40.614667 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.614767 | rdo-centos-7 |            Requires: python2-networking-bgpvpn >= 8.0.0
2019-03-22 12:47:40.614986 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.615101 | rdo-centos-7 |            Requires: openstack-neutron-lbaas >= 1:13.0.0
2019-03-22 12:47:40.615322 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.615404 | rdo-centos-7 |            Requires: openstack-neutron-ml2
2019-03-22 12:47:40.615608 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.615702 | rdo-centos-7 |            Requires: openstack-neutron >= 1:13.0.0
2019-03-22 12:47:40.615935 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.616097 | rdo-centos-7 |            Requires: openstack-ceilometer-common >= 11.0.0
2019-03-22 12:47:40.616399 | rdo-centos-7 | Error: Package: 1:python2-networking-odl-14.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-22 12:47:40.616532 | rdo-centos-7 |            Requires: python2-networking-l2gw >= 12.0.0

Patch-set: 2
Reviewer: Gerrit User 403 <403@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0